language: python
python:
  "2.7"
install:
  "./install-deps.sh"
script: make test
notifications:
  email:
    recipients:
      - ebulkin@caltech.edu
      - codyhan94@gmail.com
      - dpena@caltech.edu
