language: python
python:
  "2.7"
install:
  "./install-deps.sh"
script: make test
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bdbb5e789c52e8992d42
    on_success: change
    on_failure: always
    on_start: false
