#!/bin/bash

testrl=$(which rlwrap)
unamestr=$(uname)

if [ -z "$testrl" ]
then
    python2 -m graphene.client.client
else
    rlwrap -a -i -f "./graphene/utils/keywords.txt" python2 -m graphene.client.client
fi
